apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: strings-frontend
spec:
  replicas: 2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: strings-api
spec:
  replicas: 2
