
name: Prod CI 

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: checkout repo
        uses: actions/checkout@v2
      - 
        name: set output for short sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - 
        name: Build and push strings-api
        id: docker_strings_api_build
        uses: docker/build-push-action@v2
        with:
          context: ./strings-api
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/strings-api:prod-${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/strings-api:prod-${{ steps.vars.outputs.sha_short }}            
            ${{ secrets.DOCKERHUB_USERNAME }}/strings-api:prod
      - 
        name: Build and push strings-frontend
        id: docker_strings_frontend_build
        uses: docker/build-push-action@v2
        with:
          context: ./strings-frontend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/strings-frontend:prod-${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/strings-frontend:prod-${{ steps.vars.outputs.sha_short }}            
            ${{ secrets.DOCKERHUB_USERNAME }}/strings-frontend:prod
  update:  
    needs: [build]
    runs-on: ubuntu-latest
    env:
      version: github.run_number
    steps:
      - 
        name: Install Kustomize
        run: |
          KUSTOMIZE=3.5.5
          echo "downloading kustomize ${KUSTOMIZE}"
          curl -sL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE}/kustomize_v${KUSTOMIZE}_linux_amd64.tar.gz | \
          tar xz && sudo mv kustomize /usr/local/bin/kustomize
          kustomize version
      - 
        uses: actions/checkout@v2
        with:
          repository: 'suren-m/cndev-config'
      - 
        name: Kustomize edit
        run: |
          cd ./kustomization/prod 
          kustomize edit set image ${{ secrets.DOCKERHUB_USERNAME }}/strings-api=${{ secrets.DOCKERHUB_USERNAME }}/strings-api:prod-${{ github.run_number }}    
          kustomize edit set image ${{ secrets.DOCKERHUB_USERNAME }}/strings-frontend=${{ secrets.DOCKERHUB_USERNAME }}/strings-frontend:prod-${{ github.run_number }}    
      - 
        name: Update kustomization
        run: |          
          git config --global user.name 'workflow_action'
          git config --global user.email 'workflow_action@users.noreply.github.com'
          git commit -am "update image version on kustomization"          
      - 
        name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          labels: gitops,kustomize,argocd
          title: Publish new version
          branch: deploy/prod
          reviewers: suren-m
          assignees: suren-m
      - 
        name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      
            
          
