
name: Prod CI 

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: checkout repo
        uses: actions/checkout@v2
      - 
        name: Build and push strings-api
        id: docker_strings_api_build
        uses: docker/build-push-action@v2
        with:
          context: ./strings-api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/strings-api:latest
      - 
        name: Install Kustomize
        run: |
          KUSTOMIZE=3.5.5
          echo "downloading kustomize ${KUSTOMIZE}"
          curl -sL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE}/kustomize_v${KUSTOMIZE}_linux_amd64.tar.gz | \
          tar xz && mv kustomize /usr/local/bin/kustomize
          kustomize version
      
        
            
          
